### ISSUE TITLE
Issues connecting to Mooshimeter V1

### ISSUE THREAD

**Issue by explit7** [sigurg/VoltFish#2]
Hello sigurg.
Have some problems to connect to Mooshimeter.

I entered the BT-Address of my MooshV1 98:7B:F3:XX:XX:XX
and pressed enter. Also tried to reboot the Mosshimeter, i got no connection.
Is there a trick or something?
![photo_2018-09-21_14-09-51](https://user-images.githubusercontent.com/11852348/45880391-0f152700-bda8-11e8-9e80-96a2b50a355a.jpg)
![photo_2018-09-21_14-09-56](https://user-images.githubusercontent.com/11852348/45880393-0f152700-bda8-11e8-9507-67f78f360db3.jpg)

**Comment by sigurg** [comment]
It's supposed to work exactly like you described, but this app has never been tested on anything other than my aquafish with my meter.

Could you please check the following things:
* make sure bluetooth is enabled in jolla settings (just to be sure)
* ensure the meter is not in shipping mode
* can you connect from an android/ios device using the official app?
* does the meter have a firmware version starting with 147? (mine has 1477971088)
* check if the Bluetooth address has been saved correctly (run `cat .config/VoltFish/VoltFish.conf` in the terminal and check if "btaddr" is correct without any spaces before or after)
* run `VoltFish` from a terminal and check if there are any errors

**Comment by explit7** [comment]
With IOS Android anything is fine. Under Android i have a beta Firmware starting with 15 (1522204715)
Is it a big problem? Is a downgrade needed ?

**Comment by sigurg** [comment]
I'll try to update my mooshimeter & check that firmware, when I get home later tonight.
Have you checked the terminal output yet?

**Comment by explit7** [comment]
Thanks for the testing the new FW,sigurg.
In Terminal i doesnt found something criminal

![screenshot from 2018-09-22 20-45-27](https://user-images.githubusercontent.com/11852348/45920693-89c56b80-bea8-11e8-97ad-4584cd2e79d1.png)

![image](https://user-images.githubusercontent.com/11852348/45920716-e7f24e80-bea8-11e8-9adb-015c8f12f229.png)

![image](https://user-images.githubusercontent.com/11852348/45920735-1112df00-bea9-11e8-8ee6-4e16b690439b.png)

**Comment by sigurg** [comment]
Unfortunately I cannot find any firmware newer than 1477971088, so I can't test your firmware version.

I attached a debug build of the app (zipped, because I'm not allowed to attach RPMs), which is a lot more spammy... Could you please run that and post the output as a log file? (`VoltFish &> voltfish.log` should work to produce a log)

[VoltFish-0.1.1-1.armv7hl.rpm.zip](https://github.com/sigurg/VoltFish/files/2408390/VoltFish-0.1.1-1.armv7hl.rpm.zip)

**Comment by explit7** [comment]
Hi Sigurg.

I got the new firmware from the Mooshimeterbeta android App in the playstore.
You can opt in or just take this apk.

Unfortunately, i'm unable to start your debugging vesion at all :(



On September 23, 2018 6:46:42 AM GMT+02:00, sigurg <notifications@github.com> wrote:
>Unfortunately I cannot find any firmware newer than 1477971088, so I
>can't test your firmware version.
>
>I attached a debug build of the app (zipped, because I'm not allowed to
>attach RPMs), which is a lot more spammy... Could you please run that
>and post the output as a log file? (`VoltFish &> voltfish.log` should
>work to produce a log)
>
>[VoltFish-0.1.1-1.armv7hl.rpm.zip](https://github.com/sigurg/VoltFish/files/2408390/VoltFish-0.1.1-1.armv7hl.rpm.zip)
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sigurg/VoltFish/issues/2#issuecomment-423791686

-- 
Kind regards / Mit freundlichen Grüßen

ExPLIT IT Solutions
Pawel Radomychelski

**Comment by explit7** [comment]
Hi Sigurg. 

I got the new firmware from the Mooshimeterbeta android App in the playstore. 
You can opt in or just take this apk. Unfortunately, i'm unable to start your debugging vesion at all :( [Mooshimeter 1.0.43 (2283).apk.zip](https://github.com/sigurg/VoltFish/files/2408645/Mooshimeter.1.0.43.2283.apk.zip) 

![45948081-f2baf980-bff6-11e8-91f9-01c1befcae33](https://user-images.githubusercontent.com/11852348/45948140-272eb580-bff7-11e8-8e27-0d0d42f5291a.png)

**Comment by sigurg** [comment]
Thanks for posting the APK, as I have neither an android device with play store nor a google account, I sofar relied upon the Mooshimeter-AndroidApp github repo, but that does seem to lag behind quite a bit.

I did some testing yesterday, both with a friend's xperia and the 152xx firmware and came to the following conclusions:
* the app works as expected on an xperia x with 147xxx firmware
* 152xxx does seem to be incompatible with my app (connecting to the mooshimeter seems to work, but it does not return any readings)

So for the time being: if you want to use the sailfish app, please downgrade your moshimeter to 147xxx firmware (I will add a note to the app/readme stating the issue).

**Comment by explit7** [comment]
Thanks Sigurg!
Indeed, with 147XXX Firmware its working fine!

Thanks

Pawel


On Tuesday, 25 September 2018, sigurg wrote:
> Thanks for posting the APK, as I have neither an android device with play store nor a google account, I sofar relied upon the Mooshimeter-AndroidApp github repo, but that does seem to lag behind quite a bit.
> 
> I did some testing yesterday, both with a friend's xperia and the 152xx firmware and came to the following conclusions:
> * the app works as expected on an xperia x with 147xxx firmware
> * 152xxx does seem to be incompatible with my app (connecting to the mooshimeter seems to work, but it does not return any readings)
> 
> So for the time being: if you want to use the sailfish app, please downgrade your moshimeter to 147xxx firmware (I will add a note to the app/readme stating the issue).
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/sigurg/VoltFish/issues/2#issuecomment-42417901

-- 
Kind regards / 
Mit freundlichen Grüßen

ExPLIT IT Solutions
Pawel Radomychelski
