### ISSUE TITLE
Uploading VoltFish to Openrepos

### ISSUE THREAD

**Issue by explit7** [sigurg/VoltFish#7]
Hi Sigurg,
what about uploading Voltfish to Openrepos.net ?

It would be much easier to maintaining the versions, translations etc.
Many people simply don't know about the App, because its only on GitHub.

Thanks

**Comment by sigurg** [comment]
I definitely plan to do that, but I did not want to release the app to a larger audience without the ability to connect your meter by picking it from a list of detected devices.
Since this is now implemented, I'll put a release on openrepos soon...

**Comment by sigurg** [comment]
@explit7 @GNUuser 
uploaded to openrepos: https://openrepos.net/content/sigurg/voltfish
further releases will happen there...
