### ISSUE TITLE
use lower case in appName, instead camel case

### ISSUE THREAD

**Issue by GNUuser** [sigurg/VoltFish#9]
Please use lower case appName by matching with recent changes in favor of lower case

**Comment by sigurg** [comment]
The changes were only meant to conform with sailfish/linux package name conventions, where all RPM/package names are lower case.
Everything visible to the user (menu icon, name in app itself) is still camel case. This is behaviour is common to most sailfish apps.

**Comment by GNUuser** [comment]
i got it. thanks.

**Comment by GNUuser** [comment]
@sigurg  you are doing an exellent work on VoltFish. thanks for all the  improving and revamping on VoltFish :  )
